version: 2.1

orbs:
  node: circleci/node@1.1.6
  slack: circleci/slack@3.4.2

jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build
            - persist_to_workspace:
                root: .
                paths: '*'

  test:
    executor:
      name: node/default
    steps:
      - attach_workspace:
          at: .
      - run: echo tests will run here...
      - run: pwd
      - run: ls -a

  production-deploy:
    executor:
      name: node/default
    steps:
      - attach_workspace:
          at: .
      - run: npm run netlify:deploy

  draft-deploy:
    executor:
      name: node/default
    steps:
      - attach_workspace:
          at: .
      - run: npm run netlify:draft-deploy
      - slack/notify:
          color: '#50FA7B'
          mentions: 'Jackjon,'
          message: A draft deploy has been released and is awaiting review.
          webhook: '${SLACK_WEBHOOK}'

workflows:
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - slack/approval-notification:
          message: Pending approval
          webhook: '${SLACK_WEBHOOK}'
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - approve-production-deploy:
          type: approval
          requires:
            - slack/approval-notification
          filters:
            branches:
              only:
                - master
      - production-deploy:
          requires:
            - approve-production-deploy
          filters:
            branches:
              only:
                - master
      - draft-deploy:
          requires:
            - test
          filters:
            branches:
              ignore:
                - master
