version: 2.1

orbs:
  node: circleci/node@1.1.6

jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build
            - persist_to_workspace:
                root: .
                paths: '*'

  test:
    executor:
      name: node/default
    steps:
      - attach_workspace:
          at: .
      - run: echo tests will run here...
      - run: pwd
      - run: ls -a

  production-deploy:
    executor:
      name: node/default
    steps:
      - attach_workspace:
          at: .
      - run: npm run netlify:deploy

  draft-deploy:
    executor:
      name: node/default
    steps:
      - attach_workspace:
          at: .
      - run: npm run netlify:draft-deploy

workflows:
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - production-deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - draft-deploy:
          requires:
            - test
          filters:
            branch:
              ignore:
                - master
