version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-test-deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build
            - run: echo tests will run here...
            - run: npm run netlify:deploy
workflows:
  build-test-deploy:
    jobs:
      - build-test-deploy
